volumes:
  dbdata:

networks:
  network:

services:
  webserver:
    container_name: todo-web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./src:/var/www/src:z
      - ./public:/var/www/html:z
    networks:
      - network
    ports:
      - "8080:80"
    env_file: .env

  database:
    container_name: todo-db
    image: mariadb
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - network
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
     container_name: todo-pma
     image: phpmyadmin/phpmyadmin
     env_file: .env
     ports:
       - "8000:80"
     restart: always
     environment:
       PMA_HOST: database
     networks:
       - network
     depends_on:
       - database
