volumes:
  dbdata:
services:
  webserver:
    container_name: todo-web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./public:/var/www/html:Z
    ports:
      - "8000:80"
  database:
    container_name: todo-db
    image: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
     container_name: todo-pma
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     restart: always
     environment:
       PMA_HOST: database
     depends_on:
       - database
