volumes:
  dbdata:

services:
  webserver:
    container_name: todo-web
    restart: always
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - database
    profiles:
      - prod
    build:
        context: .
        dockerfile: Dockerfile
        target: prod

  webserver-dev:
    container_name: todo-web-dev
    restart: always
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - database
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/var/www/src:z
      - ./public:/var/www/html:z

  database:
    container_name: todo-db
    image: mariadb
    restart: always
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
     container_name: todo-pma
     image: phpmyadmin/phpmyadmin
     restart: always
     env_file: .env
     ports:
       - "8000:80"
     depends_on:
       - database
